language: cpp
dist: bionic

compiler:
- gcc
os:
- linux
- osx

env: 
- BUILD_TYPE=Debug
- BUILD_TYPE=RelWithDebInfo

addons:
  apt:
    packages:
    - cmake
    - gcc-8
    - g++-8
    - libxml2-dev
  homebrew:
    packages:
    - cmake
    - gcc@8
    - libpng
    update: true

before_install:
- if [ "$TRAVIS_OS_NAME" = "linux" ]; then 
    sudo add-apt-repository -y ppa:ubuntu-toolchain-r/test;
    sudo apt-get -q update;
    sudo apt-get -y install gcc-8 g++-8;
  fi

install:
- if [ "$TRAVIS_OS_NAME" = "linux" ]; then
    export CC=/usr/bin/gcc-8 CXX=/usr/bin/g++-8;
  fi
- if [ "$TRAVIS_OS_NAME" = "osx" ]; then
    export CC="gcc-8" CXX="g++-8";
  fi
- echo ${CC};
- echo ${CXX};
- ${CXX} --version;
- cmake --version;

before_script:
- patch -p0 < patches/leveldb-1.22.patch;
- mkdir -p build && cd build;
- cmake .. -DBEDROCK_VIZ_BUILD_TESTS=ON;
- make;
- cd ..;

script:
- cd build && ctest -V && cd ..
