language: cpp
dist: bionic

compiler:
- gcc
os:
- linux

env: 
- BUILD_TYPE=Debug
- BUILD_TYPE=RelWithDebInfo

addons:
  apt:
    packages:
    - cmake
    - gcc
    - g++
    - libxml2-dev

before_script:
- patch -p0 < patches/leveldb-1.22.patch
- mkdir build && cd build
- export CC=/usr/bin/gcc
- export CXX=/usr/bin/g++
- cmake -DBEDROCK_VIZ_BUILD_TESTS=ON ..
- make

script:
- cd build && ctest --verbose && cd ..
