language: cpp
dist: bionic

compiler:
- gcc
os:
- linux
- osx

env: 
- BUILD_TYPE=Debug
- BUILD_TYPE=RelWithDebInfo

addons:
  apt:
    packages:
    - cmake
    - libxml2-dev
  homebrew:
    packages:
    - cmake
    - gcc
    - libpng
    update: true

before_install:
# Use latest GCC-9 from ubuntu-toolchain-r PPA
- if [ "$TRAVIS_OS_NAME" = "linux" ]; then 
    sudo add-apt-repository -y ppa:ubuntu-toolchain-r/test;
    sudo apt-get -q update;
    sudo apt-get -y install gcc-9 g++-9;
  fi

install:
# Set environment variables for C/C++ Compilers
- if [ "$TRAVIS_OS_NAME" = "linux" ]; then
    export CC=/usr/bin/gcc-9 CXX=/usr/bin/g++-9;
  fi
- if [ "$TRAVIS_OS_NAME" = "osx" ]; then
    export CC="gcc-9" CXX="g++-9";
  fi
# Check that correct GCC is used 
- echo ${CC};
- echo ${CXX};
- ${CXX} --version;
- cmake --version;

before_script:
- patch -p0 < patches/leveldb-1.22.patch;
- mkdir -p build && cd build;
- cmake .. -DBEDROCK_VIZ_BUILD_TESTS=ON;
- make;
- cd ..;

script:
- cd build && ctest -V && cd ..
