language: cpp
dist: bionic

compiler:
- gcc
os:
- linux
- osx
#- windows

env: 
- BUILD_TYPE=Debug
- BUILD_TYPE=RelWithDebInfo

addons:
  apt:
    packages:
    - cmake
    - gcc-8
    - g++-8
    - libxml2-dev
  homebrew:
    packages:
    - cmake
    - gcc@8
    - libpng
    update: true

install:
- if [ "$CXX" = "g++" ]; then
    export CC=/usr/bin/gcc-8;
    export CXX=/usr/bin/g++-8;
  fi
- echo ${CC}
- echo ${CXX}
- ${CXX} --version
- cmake --version

before_script:
- patch -p0 < patches/leveldb-1.22.patch
- mkdir -p build && cd build
- cmake -DBEDROCK_VIZ_BUILD_TESTS=ON ..
- make
- cd ..

script:
- cd build && ctest --verbose && cd ..
