language: cpp
dist: bionic

compiler:
- gcc
os:
- linux
- osx
- windows

env: 
- BUILD_TYPE=Debug
- BUILD_TYPE=RelWithDebInfo

addons:
  apt:
    packages:
    - cmake
    - gcc-8
    - g++-8
    - libxml2-dev
  homebrew:
    packages:
    - cmake
    - gcc@8
    - libpng
    update: true

before_install:
- |- 
    if [ "$TRAVIS_OS_NAME" = "windows" ]; then
      git clone https://github.com/Microsoft/vcpkg.git;
      cd vcpkg;
      .\boostrap-vcpkg.bat;
      .\vcpkg integrate install;
      .\vckpg install libpng:x64-windows zlib:x64-windows libxml2:x64-windows;
      cd ..;
      choco install -y patch;
    fi

install:
- |- 
    if [ "$TRAVIS_OS_NAME" = "windows" ]; then
      echo "WIN10"
    else
      if [ "$CXX" = "g++" ]; then
        export CC="gcc-8" CXX="g++-8";
      fi
      echo ${CC};
      echo ${CXX};
      ${CXX} --version;
      cmake --version;
    fi

before_script:
- patch -p0 < patches/leveldb-1.22.patch
- mkdir -p build && cd build
- cmake -DBEDROCK_VIZ_BUILD_TESTS=ON ..
- make
- cd ..

script:
- cd build && ctest --verbose && cd ..
